---
title: "PRoteinMassSpecSim"
author: "Sebastian Malchow"
date: "4 Februar 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Goals

Aim of this project is to simulate Protein Mass Spectra from the Protein Sequence. This includes simulation of the isotope pattern, the pattern generated by several charge states which are usually observed. In a later stage the resolution of the mass spectrometer shall be included to have an idea of the influence of the resolution to the observed isotopic pattern.

Further features might be the simulation of a mass spectrum by UniProt Accession instead of Protein Sequence, which is possible by looking up the sequence from UniProt, and the generation of a comparision plot to a measured spectrum for protein identification and publication purposes.

## ToDo

* Add code to calculate chemical formula from protein sequence, allow addition of common modfications
* Utilize isotope distribution simulation from http://orgmassspec.github.io/
* Add spectra generation
* Add resolution simulation for orbitrap mass spectrometers
* Add spectra import of as a list of mass and intensity
* Plot head to tails comparision plot with ggplot



<!-- ## Usage Example -->

<!-- You can also embed plots, for example: -->

<!-- ```{r pressure, echo=FALSE} -->
<!-- plot(pressure) -->
<!-- ``` -->

<!-- Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot. -->
